
export const IMG = {
    img_1: require('./elements/1.png').default,
    img_2: require('./elements/2.png').default,
    img_3: require('./elements/3.png').default,
    img_4: require('./elements/4.png').default,
    img_5: require('./elements/5.png').default,
    img_6: require('./elements/6.png').default,
    img_7: require('./elements/7.png').default,
    img_8: require('./elements/8.png').default,
    img_9: require('./elements/9.png').default,
    img_10: require('./elements/10.png').default,
    img_11: require('./elements/11.png').default,
    img_12: require('./elements/12.png').default,
    img_13: require('./elements/13.png').default,
    img_14: require('./elements/14.png').default,
    img_15: require('./elements/15.png').default,
    img_16: require('./elements/16.png').default,
    img_17: require('./elements/17.png').default,
    img_18: require('./elements/18.png').default,
    img_19: require('./elements/19.png').default,
    img_20: require('./elements/20.png').default,
    img_21: require('./elements/21.png').default,
    img_22: require('./elements/22.png').default,
    img_23: require('./elements/23.png').default,
    img_24: require('./elements/24.png').default,
    img_25: require('./elements/25.png').default,
    img_26: require('./elements/26.png').default,
    img_27: require('./elements/27.png').default,
    img_28: require('./elements/28.png').default,
    img_29: require('./elements/29.png').default,
    img_30: require('./elements/30.png').default,

    img_163: require('./elements/163.png').default,
}